def test_imports():
    import ngbse
    import ngbse.collectors.http_web
    import ngbse.enrich.metadata_enricher
    import ngbse.scoring.scoring
    import ngbse.synth.reverse_llm
    import ngbse.export.stix_exporter
    import ngbse.forecast.forecast_engine
    import ngbse.report.docx_reporter
    assert True
